server:
  port: 80 # 设置网关服务的端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:                   # 网关路由配置
        - id: user-service      # 路由ID，必须唯一
          uri: lb://userservice # 路由的目标地址，lb表示负载均衡，后面为服务名称，也支持http
          predicates:           # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/**     # 这个是按照路径匹配，只要是以/user开头就符合要求
          filters:              # 过滤器
            - AddRequestHeader=X-Request-red, blue # 添加请求头
        - id: order-service
          uri: lb://order-service
          # 断言工厂的作用
          # 读取用户定义的断言条件，对请求做出判断
          predicates:
            - Path=/order/**
      # 过滤器的作用
      # 1.对路由的请求或响应做加工处理，比如添加请求头
      # 2.配置在路由下的过滤器只会对当前路由请求生效
      default-filters: # 默认过滤器，作用于所有的请求
        - AddRequestHeader=X-Request-red, blue
