server:
  port: 80 # 设置网关服务的端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:                   # 网关路由配置
        - id: user-service      # 路由ID，必须唯一
          uri: lb://userservice # 路由的目标地址，lb表示负载均衡，后面为服务名称，也支持http
          predicates:           # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/**     # 这个是按照路径匹配，只要是以/user开头就符合要求
          filters:              # 过滤器
            - AddRequestHeader=X-Request-red, blue # 添加请求头
        - id: order-service
          uri: lb://order-service
          # 断言工厂的作用
          # 读取用户定义的断言条件，对请求做出判断
          predicates:
            - Path=/order/**
      # 过滤器的作用
      # 1.对路由的请求或响应做加工处理，比如添加请求头
      # 2.配置在路由下的过滤器只会对当前路由请求生效
      default-filters: # 默认过滤器，作用于所有的请求
        - AddRequestHeader=X-Request-red, blue
      # 全局过滤器与网关过滤器的区别
      # 网关过滤器通过配置定义，处理逻辑是固定的，全局过滤器的逻辑需要自己写代码实现
      globalcors: # 全局处理跨域
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求头中携带的信息
            allowedCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 跨域检测的有效期
