server:
  port: 9002                                   # 服务端口
spring:
  application:
    name: user-service                         # 服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver   # 驱动全限定类名
    url: jdbc:mysql:///cloud_user?useSSL=false # 数据库连接地址
    username: root                             # 用户名
    password: 123456                           # 密码
  cloud:
    nacos:
      server-addr: localhost:8848              # nacos 服务地址
      discovery:
        cluster-name: CD                       # 配置集群的名称, 比如: CD, 成都
mybatis:
  type-aliases-package: org.example.user.pojo  # 实体类别名路径
  configuration:
    map-underscore-to-camel-case: true         # 开启下划线转驼峰
  mapper-locations: classpath:mapper/*.xml     # Mapper XML 文件地址
logging:
  level:
    org.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:9000/eureka # 注册中心
